      !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%!
      !                                                                        !
      !                    LINKED LISTS OF INTERFACE POINTS                    !
      !                                                                        !
      !%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%!

      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ! NEWIPY --
      !    ADD ONE IRREGULAR INTERFACE POINT TO THE LINKED LIST OF A IY-AXIS
      !    ALONG X-DIRECTION
      ! ARGUMENTS:
      !    IY    IN      A GIVEN IY-AXIS
      !    IX    IN      THE NODE ON THE LEFT OF THE INTERFACE POINT
      !    IFP   IN      INDEX OF THE INTERFACE POINT IN THE LIST
      !    DATA  IN/OUT  AN ELEMENT OF THE LIST FOR ONE INTERFACE POINT
      ! NOTES:
      !    ON BOTH SIDES OF EACH INTERFACE POINT, AT LEAST 2 NODES ARE REQUIRED
      !    THIS SUBROUTINE CREATES A ELEMENET TO STORE THE GEOMETRIC INFORMATION
      !    OF AN INTERFACE POINT. JUMP CONDITIONS WILL BE SET SEPERATELY IN
      !    SUBROUTINE SETFPX.
      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      SUBROUTINE NEWIPY(IY,IX,IFP,DATA)

      USE MOD_DATA

      INTEGER :: IY,IX,IFP
      TYPE(LIST_DATA) :: DATA

      REAL :: XINF,YINF,VARPHI

      YINF = YI(IY) !Y-COORDINATE OF THE INTERFACE POINT

      !INTERFACE IS CONSIDERED TO BE DRAWN IN COUNUTER-CLOCK DIRECTION
      IF (MOD(IFP,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE X DIRECTION
         CALL GAMMAX(YINF,XI(IX+1),XI(IX),XINF,VARPHI) !XINF = X-COORDINATE OF THE INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE X DIRECTION
         CALL GAMMAX(YINF,XI(IX),XI(IX+1),XINF,VARPHI) !XINF = X-COORDINATE OF THE INTERFACE POINT
      END IF

      !----- AXIS INFO
      DATA%AXTP   =  1
      DATA%AXID   =  IY
      !----- INTERFACE LOCATION AND INFO
      DATA%ID     =  IFP
      DATA%LGRD   =  IX
      DATA%THETA  =  GETNORMAL(XINF,YINF,VARPHI)
      CALL SETIFPBETA(DATA) ! OR DATA%BETA1 = IFBETA1(XINF,YINF); DATA%BETA2 = IFBETA2(XINF,YINF)
      DATA%X      =  XINF
      DATA%Y      =  YINF
      !----- INTERFACE TYPE AND INTERPLOATING NODES FOR U_TAU
      DATA%GAMMA  =  XINF-XI(IX)

      !INTERFACE POINT IS CLOSE TO THE LEFT NODE, 2 INTERPOLATING NODES ARE (IX-1, IX+1)
      IF (DATA%GAMMA .LT. TOL_ITYPE) THEN
         DATA%ITYPE = -1
      !INTERFACE POINT IS CLOSE TO THE RIGHT NODE, 2 INTERPOLATING NODES ARE (IX, IX+2)
      ELSE IF (DATA%GAMMA .GE. DX-TOL_ITYPE) THEN
         DATA%ITYPE =  1
      ELSE !INTERFACE POINT IS IN BETWEEN, 2 INTERPOLATING NODES ARE (IX, IX+1)
         DATA%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATA%WIJ       = 0.0D0
      DATA%WIJ2      = 0.0D0

      DATA%ITAU      = 0

      DATA%AUXL      = 0
      DATA%DAUXL     = 0.0D0
      DATA%AUXL_AXTP = 0
      DATA%AUXL_AXID = 0
      DATA%AUXL_X    = 0.0D0
      DATA%AUXL_Y    = 0.0D0
      DATA%IAUXL     = 0
      DATA%WAUXL     = 0.0D0

      DATA%AUXR      = 0
      DATA%DAUXR     = 0.0D0
      DATA%AUXR_AXTP = 0
      DATA%AUXR_AXID = 0
      DATA%AUXR_X    = 0.0D0
      DATA%AUXR_Y    = 0.0D0
      DATA%IAUXR     = 0
      DATA%WAUXR     = 0.0D0

      DATA%JUMP      = 0.0D0
      DATA%UTAU      = 0.0D0
      DATA%UAUXL     = 0.0D0
      DATA%UAUXR     = 0.0D0

      RETURN

      END SUBROUTINE NEWIPY

      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ! NEWIPY2 --
      !    ADD TWO INTERFACE POINTS ASSOCIATED WITH ONE CORNER POINT TO THE LINKED
      !    LIST OF A IY-AXIS ALONG X-DIRECTION
      ! ARGUMENTS:
      !    IY    IN      A GIVEN IY-AXIS
      !    IX    IN      THE NODE ON THE LEFT OF THE INTERFACE POINT
      !    IFP   IN      INDEX OF THE INTERFACE POINT IN THE LIST
      !    DATAL IN/OUT  AN ELEMENT OF THE LIST FOR THE LEFT  INTERFACE POINT
      !    DATAR IN/OUT  AN ELEMENT OF THE LIST FOR THE RIGHT INTERFACE POINT
      ! NOTES:
      !    ON BOTH SIDES OF EACH INTERFACE POINT, AT LEAST 2 NODES ARE REQUIRED
      !    THIS SUBROUTINE CREATES A ELEMENET TO STORE THE GEOMETRIC INFORMATION
      !    OF AN INTERFACE POINT. JUMP CONDITIONS WILL BE SET SEPERATELY IN
      !    SUBROUTINE SETFPX2.
      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      SUBROUTINE NEWIPY2(IY,IX,IFP,DATAL,DATAR)

      USE MOD_DATA

      INTEGER :: IX,IY,IFP
      TYPE(LIST_DATA) :: DATAL,DATAR

      REAL :: XINFL,YINFL,VARPHIL !COORDINATES OF THE LEFT  INTERFACE POINT
      REAL :: XINFR,YINFR,VARPHIR !COORDINATES OF THE RIGHT INTERFACE POINT

      !----- LEFT INTERFACE POINT
      YINFL = YI(IY) !Y-COORDINATE OF THE LEFT INTERFACE POINT
      IF (MOD(IFP,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE X DIRECTION
         CALL GAMMAX(YINFL,XI(IX+1),XI(IX),XINFL,VARPHIL) !XINFL=X-COORDINATE OF THE LEFT INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE X DIRECTION
         CALL GAMMAX(YINFL,XI(IX),XI(IX+1),XINFL,VARPHIL) !XINFL=X-COORDINATE OF THE LEFT INTERFACE POINT
      END IF

      DATAL%AXTP   =  1
      DATAL%AXID   =  IY
      DATAL%ID     = -IFP
      DATAL%LGRD   =  IX
      DATAL%THETA  =  GETNORMAL(XINFL,YINFL,VARPHIL)

      CALL SETIFPBETA(DATAL) ! OR DATAL%BETA1 = IFBETA1(XINFL,YINFL); DATAL%BETA2 = IFBETA2(XINFL,YINFL)

      DATAL%X      =  XINFL
      DATAL%Y      =  YINFL
      DATAL%GAMMA  =  XINFL-XI(IX)

      !NOTICE: TYPE FOR TWO INTERFACE POINTS OF A CONRNER POINT IS SLIGHTLY DIFFERNT FROM THAT OF
      !        THE IRREGULAR INTERFACE POINTS
      IF (DATAL%GAMMA .LE. TOL_ITYPE) THEN !LEFT INTERFACE POINT IS CLOSE TO THE LEFT NODE
         DATAL%ITYPE = -1
      ELSE !LEFT INTERFACE POINT IS IN BETWEEN
         DATAL%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATAL%WIJ       = 0.0D0
      DATAL%WIJ2      = 0.0D0

      DATAL%ITAU      = 0

      DATAL%AUXL      = 0
      DATAL%DAUXL     = 0.0D0
      DATAL%AUXL_AXTP = 0
      DATAL%AUXL_AXID = 0
      DATAL%AUXL_X    = 0.0D0
      DATAL%AUXL_Y    = 0.0D0
      DATAL%IAUXL     = 0
      DATAL%WAUXL     = 0.0D0

      DATAL%AUXR      = 0
      DATAL%DAUXR     = 0.0D0
      DATAL%AUXR_AXTP = 0
      DATAL%AUXR_AXID = 0
      DATAL%AUXR_X    = 0.0D0
      DATAL%AUXR_Y    = 0.0D0
      DATAL%IAUXR     = 0
      DATAL%WAUXR     = 0.0D0

      DATAL%JUMP      = 0.0D0
      DATAL%UTAU      = 0.0D0
      DATAL%UAUXL     = 0.0D0
      DATAL%UAUXR     = 0.0D0

      !----- RIGHT INTERFACE POINT
      YINFR = YI(IY) !Y-COORDINATE OF THE RIGHT INTERFACE POINT

      IF (MOD(IFP+1,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE X DIRECTION
         CALL GAMMAX(YINFR,XI(IX+2),XI(IX+1),XINFR,VARPHIR) !XINFR=X-COORDINATE OF THE RIGHT INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE X DIRECTION
         CALL GAMMAX(YINFR,XI(IX+1),XI(IX+2),XINFR,VARPHIR) !XINFR=X-COORDINATE OF THE RIGHT INTERFACE POINT
      END IF

      DATAR%AXTP   =  1
      DATAR%AXID   =  IY
      DATAR%ID     = -(IFP+1)
      DATAR%LGRD   =  IX+1
      DATAR%THETA  =  GETNORMAL(XINFR,YINFR,VARPHIR)

      CALL SETIFPBETA(DATAR) !OR DATAR%BETA1 = IFBETA1(XINFR,YINFR); DATAR%BETA2 = IFBETA2(XINFR,YINFR)

      DATAR%X      =  XINFR
      DATAR%Y      =  YINFR
      DATAR%GAMMA  =  XINFR-XI(IX+1)

      !NOTICE: THE TYPE FOR TWO INTERFACE POINTS OF A CONRNER POINT IS SLIGHTLY DIFFERNT FROM THAT OF
      !        THE IRREGULAR INTERFACE POINTS
      IF (DATAR%GAMMA .GT. DX-TOL_ITYPE) THEN !RIGHT INTERFACE POINT IS CLOSE TO THE RIGHT NODE
         DATAR%ITYPE =  1
      ELSE !RIGHT INTERFACE POINT IS IN BETWEEN
         DATAR%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATAR%WIJ       = 0.0D0
      DATAR%WIJ2      = 0.0D0

      DATAR%ITAU      = 0

      DATAR%AUXL      = 0
      DATAR%DAUXL     = 0.0D0
      DATAR%AUXL_AXTP = 0
      DATAR%AUXL_AXID = 0
      DATAR%AUXL_X    = 0.0D0
      DATAR%AUXL_Y    = 0.0D0
      DATAR%IAUXL     = 0
      DATAR%WAUXL     = 0.0D0

      DATAR%AUXR      = 0
      DATAR%DAUXR     = 0.0D0
      DATAR%AUXR_AXTP = 0
      DATAR%AUXR_AXID = 0
      DATAR%AUXR_X    = 0.0D0
      DATAR%AUXR_Y    = 0.0D0
      DATAR%IAUXR     = 0
      DATAR%WAUXR     = 0.0D0

      DATAR%JUMP      = 0.0D0
      DATAR%UTAU      = 0.0D0
      DATAR%UAUXL     = 0.0D0
      DATAR%UAUXR     = 0.0D0

      !TAKING BOTH LEFT AND RIGHT INTERFACE POINTS INTO CONSIDERATION BASED ON THE GAMMA VALUE
      IF (DATAL%GAMMA .LE. DX-DATAR%GAMMA) THEN
         DATAL%ITYPE = -2
      ELSE IF (DATAL%GAMMA .GT. DX-DATAR%GAMMA) THEN
         DATAR%ITYPE =  2
      ELSE
         WRITE(*,*) "NEWIPY2: ONE CORNER PT IS TOO CLOSE TO THE BOUNDARY. SPATIAL REFINEMENT IS REQUIRED..."
         STOP
      END IF

      RETURN

      END SUBROUTINE NEWIPY2

      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ! NEWIPX --
      !    ADD ONE IRREGULAR INTERFACE POINT TO THE LINKED LIST OF A IX GRID LINE
      !    ALONG Y-DIRECTION
      ! ARGUMENTS:
      !    IX    IN      A GIVEN IX-AXIS
      !    IY    IN      THE NODE ON THE LEFT OF THE INTERFACE POINT
      !    IFP   IN      INDEX OF THE INTERFACE POINT IN THE LIST
      !    DATA  IN/OUT  AN ELEMENT OF THE LIST FOR ONE INTERFACE POINT
      ! NOTES:
      !    ON BOTH SIDES OF EACH INTERFACE POINT, AT LEAST 2 NODES ARE REQUIRED
      !    THIS SUBROUTINE CREATES A ELEMENET TO STORE THE GEOMETRIC INFORMATION
      !    OF AN INTERFACE POINT. JUMP CONDITIONS WILL BE SET SEPERATELY IN
      !    SUBROUTINE SETFPY.
      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      SUBROUTINE NEWIPX(IX,IY,IFP,DATA)

      USE MOD_DATA

      INTEGER :: IX,IY,IFP
      TYPE(LIST_DATA) :: DATA

      REAL :: XINF,YINF,VARPHI

      XINF = XI(IX) !X-COORDINATE OF THE INTERFACE POINT

      IF (MOD(IFP,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE Y DIRECTION
         CALL GAMMAY(XINF,YI(IY+1),YI(IY),YINF,VARPHI) !YINF = Y-COORDINATE OF THE INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE Y DIRECTION
         CALL GAMMAY(XINF,YI(IY),YI(IY+1),YINF,VARPHI) !YINF = Y-COORDINATE OF THE INTERFACE POINT
      END IF

      !----- AXIS INFO
      DATA%AXTP   =  0
      DATA%AXID   =  IX
      !----- INTERFACE LOCATION AND INFO
      DATA%ID     =  IFP
      DATA%LGRD   =  IY
      DATA%THETA  =  GETNORMAL(XINF,YINF,VARPHI)
      CALL SETIFPBETA(DATA) ! OR DATA%BETA1 = IFBETA1(XINF,YINF); DATA%BETA2 = IFBETA2(XINF,YINF)
      DATA%X      =  XINF
      DATA%Y      =  YINF
      !----- INTERFACE TYPE AND INTERPLOATING NODES FOR U_TAU
      DATA%GAMMA  =  YINF-YI(IY)

      IF (DATA%GAMMA .LE. TOL_ITYPE) THEN !INTERFACE POINT IS CLOSE TO THE LEFT NODE
         DATA%ITYPE = -1
      ELSE IF (DATA%GAMMA .GE. DX-TOL_ITYPE) THEN !INTERFACE POINT IS CLOSE TO THE RIGHT NODE
         DATA%ITYPE =  1
      ELSE !INTERFACE POINT IS IN BETWEEN
         DATA%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATA%WIJ       = 0.0D0
      DATA%WIJ2      = 0.0D0

      DATA%ITAU      = 0

      DATA%AUXL      = 0
      DATA%DAUXL     = 0.0D0
      DATA%AUXL_AXTP = 0
      DATA%AUXL_AXID = 0
      DATA%AUXL_X    = 0.0D0
      DATA%AUXL_Y    = 0.0D0
      DATA%IAUXL     = 0
      DATA%WAUXL     = 0.0D0

      DATA%AUXR      = 0
      DATA%DAUXR     = 0.0D0
      DATA%AUXR_AXTP = 0
      DATA%AUXR_AXID = 0
      DATA%AUXR_X    = 0.0D0
      DATA%AUXR_Y    = 0.0D0
      DATA%IAUXR     = 0
      DATA%WAUXR     = 0.0D0

      DATA%JUMP      = 0.0D0
      DATA%UTAU      = 0.0D0
      DATA%UAUXL     = 0.0D0
      DATA%UAUXR     = 0.0D0

      RETURN

      END SUBROUTINE NEWIPX

      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ! NEWIPX2 --
      !    ADD TWO INTERFACE POINTS ASSOCIATED WITH ONE CORNER POINT TO THE LINKED
      !    LIST OF A IY-AXIS ALONG X-DIRECTION
      ! ARGUMENTS:
      !    IX    IN      A GIVEN IX-AXIS
      !    IY    IN      THE NODE ON THE LEFT OF THE INTERFACE POINT
      !    IFP   IN      INDEX OF THE INTERFACE POINT IN THE LIST
      !    DATAL IN/OUT  AN ELEMENT OF THE LIST FOR THE LEFT  INTERFACE POINT
      !    DATAR IN/OUT  AN ELEMENT OF THE LIST FOR THE RIGHT INTERFACE POINT
      ! NOTES:
      !    ON BOTH SIDES OF EACH INTERFACE POINT, AT LEAST 2 NODES ARE REQUIRED
      !    THIS SUBROUTINE CREATES A ELEMENET TO STORE THE GEOMETRIC INFORMATION
      !    OF AN INTERFACE POINT. JUMP CONDITIONS WILL BE SET SEPERATELY IN
      !    SUBROUTINE SETFPY2.
      !~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      SUBROUTINE NEWIPX2(IX,IY,IFP,DATAL,DATAR)

      USE MOD_DATA

      INTEGER :: IX,IY,IFP
      TYPE(LIST_DATA) :: DATAL,DATAR

      REAL :: XINFL,YINFL,VARPHIL !COORDINATES OF THE LEFT  INTERFACE POINT
      REAL :: XINFR,YINFR,VARPHIR !COORDINATES OF THE RIGHT INTERFACE POINT

      !----- LOWER INTERFACE POINT
      XINFL = XI(IX) !X-COORDINATE OF THE LEFT INTERFACE POINT

      IF (MOD(IFP,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE X DIRECTION
         CALL GAMMAY(XINFL,YI(IY+1),YI(IY),YINFL,VARPHIL) !YINFL=Y-COORDINATE OF THE LEFT INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE X DIRECTION
         CALL GAMMAY(XINFL,YI(IY),YI(IY+1),YINFL,VARPHIL) !YINFL=Y-COORDINATE OF THE LEFT INTERFACE POINT
      END IF

      DATAL%AXTP   =  0
      DATAL%AXID   =  IX
      DATAL%ID     = -IFP
      DATAL%LGRD   =  IY
      DATAL%THETA  =  GETNORMAL(XINFL,YINFL,VARPHIL)

      CALL SETIFPBETA(DATAL) !OR DATAL%BETA1 = IFBETA1(XINFL,YINFL); DATAL%BETA2 = IFBETA2(XINFL,YINFL)

      DATAL%X      =  XINFL
      DATAL%Y      =  YINFL
      DATAL%GAMMA  =  YINFL-YI(IY)

      !NOTICE: THE TYPE FOR TWO INTERFACE POINTS OF A CONRNER POINT IS SLIGHTLY DIFFERNT FROM THAT OF
      !        THE IRREGULAR INTERFACE POINTS
      IF (DATAL%GAMMA .LE. TOL_ITYPE) THEN !LOWER INTERFACE POINT IS CLOSE TO THE LOWER NODE
         DATAL%ITYPE = -1
      ELSE !LOWER INTERFACE POINT IS IN BETWEEN
         DATAL%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATAL%WIJ       = 0.0D0
      DATAL%WIJ2      = 0.0D0

      DATAL%ITAU      = 0

      DATAL%AUXL      = 0
      DATAL%DAUXL     = 0.0D0
      DATAL%AUXL_AXTP = 0
      DATAL%AUXL_AXID = 0
      DATAL%AUXL_X    = 0.0D0
      DATAL%AUXL_Y    = 0.0D0
      DATAL%IAUXL     = 0
      DATAL%WAUXL     = 0.0D0

      DATAL%AUXR      = 0
      DATAL%DAUXR     = 0.0D0
      DATAL%AUXR_AXTP = 0
      DATAL%AUXR_AXID = 0
      DATAL%AUXR_X    = 0.0D0
      DATAL%AUXR_Y    = 0.0D0
      DATAL%IAUXR     = 0
      DATAL%WAUXR     = 0.0D0

      DATAL%JUMP      = 0.0D0
      DATAL%UTAU      = 0.0D0
      DATAL%UAUXL     = 0.0D0
      DATAL%UAUXR     = 0.0D0

      !----- UPPER INTERFACE POINT
      XINFR = XI(IX) !X-COORDINATE OF THE RIGHT INTERFACE POINT

      IF (MOD(IFP+1,2) .EQ. 1) THEN !OMEGA^+ -> OMEGA^-, THE NORMAL DIRECTION IS OPPOSITE TO POSITIVE X DIRECTION
         CALL GAMMAY(XINFR,YI(IY+2),YI(IY+1),YINFR,VARPHIR) !YINFR=Y-COORDINATE OF THE RIGHT INTERFACE POINT
      ELSE !OMEGA^- -> OMEGA^+, THE NORMAL DIRECTION IS SAME AS POSITIVE X DIRECTION
         CALL GAMMAY(XINFR,YI(IY+1),YI(IY+2),YINFR,VARPHIR) !YINFR=Y-COORDINATE OF THE RIGHT INTERFACE POINT
      END IF

      DATAR%AXTP   =  0
      DATAR%AXID   =  IX
      DATAR%ID     = -(IFP+1)
      DATAR%LGRD   =  IY+1
      DATAR%THETA  =  GETNORMAL(XINFR,YINFR,VARPHIR)

      CALL SETIFPBETA(DATAR) !OR DATAR%BETA1 = IFBETA1(XINFR,YINFR); DATAR%BETA2 = IFBETA2(XINFR,YINFR)

      DATAR%X      =  XINFR
      DATAR%Y      =  YINFR
      DATAR%GAMMA  =  YINFR-YI(IY+1)

      !NOTICE: THE TYPE FOR TWO INTERFACE POINTS OF A CONRNER POINT IS SLIGHTLY DIFFERNT FROM THAT OF
      !        THE IRREGULAR INTERFACE POINTS
      IF (DATAR%GAMMA .GT. DX-TOL_ITYPE) THEN !UPPER INTERFACE POINT IS CLOSE TO THE UPPER NODE
         DATAR%ITYPE =  1
      ELSE !UPPER INTERFACE POINT IS IN BETWEEN
         DATAR%ITYPE =  0
      END IF

      !----- INITIALIZE THE REST COMPONENTS
      DATAR%WIJ       = 0.0D0
      DATAR%WIJ2      = 0.0D0

      DATAR%ITAU      = 0

      DATAR%AUXL      = 0
      DATAR%DAUXL     = 0.0D0
      DATAR%AUXL_AXTP = 0
      DATAR%AUXL_AXID = 0
      DATAR%AUXL_X    = 0.0D0
      DATAR%AUXL_Y    = 0.0D0
      DATAR%IAUXL     = 0
      DATAR%WAUXL     = 0.0D0

      DATAR%AUXR      = 0
      DATAR%DAUXR     = 0.0D0
      DATAR%AUXR_AXTP = 0
      DATAR%AUXR_AXID = 0
      DATAR%AUXR_X    = 0.0D0
      DATAR%AUXR_Y    = 0.0D0
      DATAR%IAUXR     = 0
      DATAR%WAUXR     = 0.0D0

      DATAR%JUMP      = 0.0D0
      DATAR%UTAU      = 0.0D0
      DATAR%UAUXL     = 0.0D0
      DATAR%UAUXR     = 0.0D0

      !TAKING BOTH LEFT AND RIGHT INTERFACE POINTS INTO CONSIDERATION BASED ON THE GAMMA VALUE
      IF (DATAL%GAMMA .LE. DX-DATAR%GAMMA) THEN
         DATAL%ITYPE = -2
      ELSE IF (DATAL%GAMMA .GT. DX-DATAR%GAMMA) THEN
         DATAR%ITYPE =  2
      ELSE
         WRITE(*,*) "NEWIPX2: ONE CORNER PT IS TOO CLOSE TO THE BOUNDARY. SPATIAL REFINEMENT IS REQUIRED..."
         STOP
      END IF

      RETURN

      END SUBROUTINE NEWIPX2
