      MODULE MOD_TIME_STEPPER

      USE MOD_MIB2D

      IMPLICIT NONE

      PRIVATE
!      PUBLIC :: ADID1           !ADID1 METHOD
       PUBLIC :: ADIPR           !PEACEMAN RACHFORD ADI
!      PUBLIC :: ADIPRSETUP      !PEACEMAN RACHFORD ADI
!      PUBLIC :: IMEULER,IESETUP !IMPLICIT EULER METHOD
!      PUBLIC :: CN,CNSETUP      !CRANK-NICOLSON
!      PUBLIC :: EIGENSTAB       !STABILITY ANALYSIS VIA PRINCIPLE EIGENVALUE

      CONTAINS

       INCLUDE "mod_time_adicommon.f90"
!      INCLUDE "mod_time_adid1.f90"     !ADID1 METHOD
       INCLUDE "mod_time_adipr.f90"     !PEACEMAN RACHFORD ADI
!      INCLUDE "mod_time_ie.f90"        !IMPLICIT EULER METHOD
!      INCLUDE "mod_time_cn.f90"        !CRANK-NICOLSON
!      INCLUDE "mod_time_stability.f90" !STABILITY ANALYSIS VIA PRINCIPLE EIGENVALUE

      END MODULE MOD_TIME_STEPPER
