      MODULE MOD_TIME_STEPPER

      USE MOD_MIB2D

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: ADID1           !DOUGLAS ADI
      PUBLIC :: ADIPR           !PEACEMAN RACHFORD ADI
!     PUBLIC :: IMEULER,IESETUP !IMPLICIT EULER
!     PUBLIC :: CN,CNSETUP      !CRANK-NICOLSON
!     PUBLIC :: EIGENSTAB       !STABILITY ANALYSIS VIA PRINCIPLE EIGENVALUE
!     PUBLIC :: D_XX,D_YY       !FD FORMULA FOR 2ND ORDER DERIVATIVE D_XX AND D_YY

      INTERFACE D_XX
         MODULE PROCEDURE DXX_ADIL,DXX_RHS
      END INTERFACE D_XX

      INTERFACE D_YY
         MODULE PROCEDURE DYY_ADIL,DYY_RHS
      END INTERFACE D_YY

      CONTAINS

      INCLUDE "mod_time_fdopts.f90"    !FINITE DIFF. OPERATORS FOR D_XX AND D_YY WITH MIB
      INCLUDE "mod_time_adi.f90"       !SHARD COMMON SUBROUTINES BY ADI-TYPE METHODS
      INCLUDE "mod_time_adid1.f90"     !DOUGLAS ADI
      INCLUDE "mod_time_adiprnew.f90"  !PEACEMAN RACHFORD ADI
!     INCLUDE "mod_time_ie.f90"        !IMPLICIT EULER
!     INCLUDE "mod_time_cn.f90"        !CRANK-NICOLSON
!     INCLUDE "mod_time_stability.f90" !STABILITY ANALYSIS VIA PRINCIPLE EIGENVALUE

      END MODULE MOD_TIME_STEPPER
